"""add had_knowledge_search and had_off_topic to conversation_sessions

Revision ID: 3e2b3f3c57af
Revises: 7aadec48ca4e
Create Date: 2026-09-17 04:21:27.613791
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '3e2b3f3c57af'
down_revision: Union[str, None] = '7aadec48ca4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default=false ตอน backfill แถวเก่าที่มีอยู่แล้ว (700+ แถว) — ไม่งั้น ADD COLUMN NOT NULL
    # จะพังทันทีเพราะแถวเก่าไม่มีค่าให้ ข้อมูลเก่าเหล่านี้ไม่มีทาง derive true/false ย้อนหลังได้จริง
    # (ค่าดิบ knowledge_search_called/off_topic_flagged เดิมทิ้งไปตั้งแต่ session_tracker.py insert
    # เสร็จ ไม่เคยถูกเก็บไว้ที่ไหนก่อนหน้านี้เลย) — เท่ากับ False ทั้งคู่คือค่าที่ตรงความจริงที่สุดที่ทำ
    # ได้ (แถวเก่าจะไปตกอยู่ในกลุ่ม "ทักทายเฉยๆ" ของ AnswerStatusBars ซึ่งไม่ได้ผิดไปจากที่รู้จริง)
    op.add_column(
        'conversation_sessions',
        sa.Column('had_knowledge_search', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        'conversation_sessions',
        sa.Column('had_off_topic', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_sessions', 'had_off_topic')
    op.drop_column('conversation_sessions', 'had_knowledge_search')
    # ### end Alembic commands ###
