"""conversation turns and session analytics fields

Revision ID: 7aadec48ca4e
Revises: 8d76d39db984
Create Date: 2026-09-08 14:22:50.632102
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '7aadec48ca4e'
down_revision: Union[str, None] = '8d76d39db984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ws_connection_id', sa.String(length=36), nullable=False),
    sa.Column('speaker', sa.String(length=8), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_turns_ws_connection_id'), 'conversation_turns', ['ws_connection_id'], unique=False)
    op.add_column('conversation_sessions', sa.Column('other_hint', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_sessions', 'other_hint')
    op.drop_index(op.f('ix_conversation_turns_ws_connection_id'), table_name='conversation_turns')
    op.drop_table('conversation_turns')
    # ### end Alembic commands ###
